---
title: "DataCleanPercentage"
author: "mia"
date: "2024-09-29"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)      
library(readxl)    
library(janitor)   
library(stringr)   
library(tidyr)     
library(dplyr)
library(knitr)
library(ggplot2)
library(factoextra)
```

```{r}
raw_bp <- read.csv(here("ZIPallFiles","AHSnpa11bp.csv"), header=TRUE)
raw_bb <- read.csv(here("ZIPallFiles","AHSnpa11bb.csv"), header=TRUE)
bp_bb <- inner_join(raw_bp, raw_bb, by = "ABSPID")

raw_bsp <- read.csv(here("ZIPallFiles","inp13bsp.csv"), header=TRUE)
raw_bcn <- read.csv(here("ZIPallFiles","inp13bcn.csv"), header=TRUE)
raw_bhh <- read.csv(here("ZIPallFiles","inp13bhh.csv"), header=TRUE)

merged_data1 <- merge(raw_bsp, raw_bcn, by = c("ABSGID","ABSHID"))
merged_data2<- merge(merged_data1, raw_bhh,by = c("ABSHID"))
bsp_bcn_bhh <- merged_data2 %>%
  rename(ABSPID = ABSHID,AGEC =AGEEC)
```

```{r}
Data1 <- bp_bb %>% 
  select(
    ABSPID, HYPBC, SABDYMS, SF2SA1QN, AGEC, SEX, BMISC, SYSTOL, DIASTOL, 
    POTAST1, POTAST2, SODIUMT1, SODIUMT2, PROPER1, PROPER2, FATPER1, FATPER2, 
    LAPER1, LAPER2, ALAPER1, ALAPER2, CHOPER1, CHOPER2, SUGPER1, SUGPER2, 
    STARPER1, STARPER2, ALCPER1, ALCPER2, TRANPER1, TRANPER2, FIBRPER1, FIBRPER2, 
    MONOPER1, MONOPER2, POLYPER1, POLYPER2
  ) %>% 
  rename(SOCIAL = SF2SA1QN) %>% 
  mutate(
    HYPBC = as.factor(HYPBC),
    SEX = as.factor(SEX),
    SOCIAL = as.factor(SOCIAL),
    BMISC = na_if(na_if(BMISC, 99), 98),
    SYSTOL = na_if(na_if(na_if(SYSTOL,0),998),999),
    DIASTOL = na_if(na_if(na_if(DIASTOL,0),998),999),
    POTAST = (POTAST1 + POTAST2) / 2,
    SODIUMT = (SODIUMT1 + SODIUMT2) / 2,
    PROPER = (PROPER1 + PROPER2) / 2,
    FATPER = (FATPER1 + FATPER2) / 2,
    LAPER = (LAPER1 + LAPER2) / 2,
    ALAPER = (ALAPER1 + ALAPER2) / 2,
    CHOPER = (CHOPER1 + CHOPER2) / 2,
    SUGPER = (SUGPER1 + SUGPER2) / 2,
    STARPER = (STARPER1 + STARPER2) / 2,
    ALCPER = (ALCPER1 + ALCPER2) / 2,
    TRANPER = (TRANPER1 + TRANPER2) / 2,
    FIBRPER = (FIBRPER1 + FIBRPER2) / 2,
    MONOPER = (MONOPER1 + MONOPER2) / 2,
    POLYPER = (POLYPER1 + POLYPER2) / 2,
    Hypertension = as.factor(case_when(
    SYSTOL >= 140 | DIASTOL >= 90 ~ 1,
    TRUE ~ 0
  ))) %>%
  filter(
    AGEC >= 18, 
    HYPBC == 5,
    SABDYMS != 4
    ) %>%
  select(sort(c("ABSPID", "SOCIAL", "AGEC", "SEX", "BMISC", 
                "SYSTOL", "DIASTOL", "SODIUMT", "POTAST", 
                grep("PER$", names(.), value = TRUE), "Hypertension")))

summary(Data1)
```

```{r}
Data2 <- bsp_bcn_bhh %>%
  select(
    ABSPID, AGEC, SEX, BMISC,SYSTOL, DIASTOL, ICD10ME,SABDYMS,SF2SA1DB,
    POTAST1, POTAST2, SODIUMT1, SODIUMT2, PROPER1, PROPER2, FATPER1, FATPER2, 
    LAPER1, LAPER2, ALAPER1, ALAPER2, CHOPER1, CHOPER2, SUGPER1, SUGPER2, 
    STARPER1, STARPER2, ALCPER1, ALCPER2, TRANPER1, TRANPER2, FIBRPER1, FIBRPER2, 
    MONOPER1, MONOPER2, POLYPER1, POLYPER2
  ) %>%
  rename(SOCIAL = SF2SA1DB) %>%
  mutate(
    ICD10ME = as.factor(ICD10ME),
    SEX = as.factor(SEX),
    SOCIAL = as.factor(SOCIAL),
    SABDYMS = as.factor(SABDYMS),
    BMISC = na_if(na_if(BMISC, 99), 98),
    SYSTOL = na_if(na_if(na_if(SYSTOL,0),998),999),
    DIASTOL = na_if(na_if(na_if(DIASTOL,0),998),999),
    POTAST = (POTAST1 + POTAST2) / 2, 
    SODIUMT = (SODIUMT1 + SODIUMT2) / 2,
    PROPER = (PROPER1 + PROPER2) / 2,
    FATPER = (FATPER1 + FATPER2) / 2,
    LAPER = (LAPER1 + LAPER2) / 2,
    ALAPER = (ALAPER1 + ALAPER2) / 2,
    CHOPER = (CHOPER1 + CHOPER2) / 2,
    SUGPER = (SUGPER1 + SUGPER2) / 2,
    STARPER = (STARPER1 + STARPER2) / 2,
    ALCPER = (ALCPER1 + ALCPER2) / 2,
    TRANPER = (TRANPER1 + TRANPER2) / 2,
    FIBRPER = (FIBRPER1 + FIBRPER2) / 2,
    MONOPER = (MONOPER1 + MONOPER2) / 2,
    POLYPER = (POLYPER1 + POLYPER2) / 2,
    Hypertension = as.factor(case_when(
    SYSTOL >= 140 | DIASTOL >= 90 ~ 1,
    TRUE ~ 0))) %>%
  filter(
    AGEC >= 18, 
    !ICD10ME %in% c(7, 20),
    SABDYMS != 4) %>%
  select(sort(c("ABSPID", "SOCIAL", "AGEC", "SEX", "BMISC", 
                "SYSTOL", "DIASTOL", "SODIUMT", "POTAST", 
                grep("PER$", names(.), value = TRUE), "Hypertension")))

summary(Data2)
```

```{r}
PerData <- bind_rows(Data1,Data2)
summary(PerData)
save(PerData, file = "PercentageData.RData")

PerDataNon <- Data1
save(PerDataNon, file ="PercentageDataNon.RData")

PerDataInd <- Data2
save(PerDataInd, file ="PercentageDataInd.RData")
```
