---
title: "Untitled"
author: "mia"
date: "2024-09-12"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)      
library(readxl)    
library(janitor)   
library(stringr)   
library(tidyr)     
library(dplyr)
library(knitr)
```
# Variable Selection
```{r, message=FALSE}
raw_bp <- read.csv(here("ZIPallFiles","AHSnpa11bp.csv"), header=TRUE)
raw_bb <- read.csv(here("ZIPallFiles","AHSnpa11bb.csv"), header=TRUE)

bp_bb <- bind_rows(raw_bp, raw_bb)

X_all_File_variables <- read_excel("ZIPallFiles/_all.File.variables.xlsx", 
    sheet = "Variables", col_names = FALSE)

X_all_File_variables <- X_all_File_variables %>%
  rename(
    Survey = `...1`,
    Name = `...2`,
    VariableNames = `...3`,
    Description = `...4`
  ) %>%
  filter(Name %in% c("AHSnpa11bp", "AHSnpa11ba"))
```
## Variables selection
```{r}
bb_bp_filtered <- bp_bb %>% #variable selections
  select(
    ABSPID, HYPBC, SYSTOL, DIASTOL, 
    AGEC, SEX, BMISC,
    EXREGUIC, EXREGUID,
    ENERGYT1, ENERGYF1, ENERGYT2, ENERGYF2, 
    ENRGYT1, ENRGYF1, ENRGYT2, ENRGYF2, 
    FIBRET1, FIBREF1, FIBRES1, 
    FIBRET2, FIBREF2, FIBRES2
  ) %>% #convert sex and hypbc to factor
  mutate(
    SEX = as.factor(SEX),
    HYPBC = as.factor(HYPBC),
    EXREGUIC = as.factor(EXREGUIC),
    EXREGUID = as.factor(EXREGUID)
  ) %>% #set values as NAs, different columns has different values for na
  mutate(across(where(is.numeric), ~ case_when(
    . %in% c(9996, 9999) ~ NA_real_,
    . %in% c(99.00, 98.00) & cur_column() == "BMISC" ~ NA_real_,
    . %in% c(999, 998, 0) & cur_column() %in% c("SYSTOL", "DIASTOL") ~ NA_real_,
    TRUE ~ .
  ))) %>% #remove rows if has na
  drop_na()
#HYPBC remove == 1,2,3
#FIBRES1 set greater than 9 is na
#EXREGUID reove == 0,9
summary(bb_bp_filtered)
```

```{r}
bb_bp_long <- bb_bp_filtered %>%
  select(FIBRES1, FIBRES2, EXLWMBC, EXLWVBC, ENERGYT2, ENERGYF2, ENRGYT2, ENRGYF2) %>%
  pivot_longer(cols = everything(), names_to = "Variable", values_to = "Value")

# Create the boxplot
ggplot(bb_bp_long, aes(x = Variable, y = Value)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Boxplot of Selected Variables",
       x = "Variable",
       y = "Value")
```
```{r}
bb_bp_long <- bb_bp_filtered %>%
  select(FIBRES1, FIBRES2) %>%
  pivot_longer(cols = everything(), names_to = "Variable", values_to = "Value")

# Create the boxplot
ggplot(bb_bp_long, aes(x = Variable, y = Value)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Boxplot of Selected Variables",
       x = "Variable",
       y = "Value")
```

```{r}
new <- bb_bp_filtered
save(new, file = "NewVariables.RData")
```