---
title: "SimpleAnalysis"
author: "mia"
date: "2024-08-31"
output: 
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: true
    code_folding: hide
---

```{r setup, include=FALSE}
library(readr)
library(ggplot2)
library(reshape2)
```

```{r}
data <- read.csv("ResponseVariables_Cleaned.csv", stringsAsFactors = FALSE)
```
# Outlier
# Proportion Table
# HeatMap
```{r}
data_for_heatmap <- data[, !(names(data) %in% "ABSPID")]

# Calculate the correlation matrix for numeric variables
cor_matrix <- cor(data_for_heatmap, use = "complete.obs")

# Melt the correlation matrix to a long format
cor_melted <- melt(cor_matrix)

# Create the heatmap using ggplot2
ggplot(cor_melted, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0, limit = c(-1, 1), name = "Correlation") +
  theme_minimal() +
  labs(title = "Heatmap of Correlation Matrix",
       x = "Variables",
       y = "Variables") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```