---
title: "Variables"
author: "mia"
date: "2024-08-29"
output: 
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: true
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)      
library(readxl)    
library(janitor)   
library(stringr)   
library(tidyr)     
library(dplyr)
library(knitr)
```
# Variable Selection
```{r, message=FALSE}
raw_bp <- read.csv(here("ZIPallFiles","AHSnpa11bp.csv"), header=TRUE)
raw_bb <- read.csv(here("ZIPallFiles","AHSnpa11bb.csv"), header=TRUE)

X_all_File_variables <- read_excel("ZIPallFiles/_all.File.variables.xlsx", 
    sheet = "Variables", col_names = FALSE)

X_all_File_variables <- X_all_File_variables %>%
  rename(
    Survey = `...1`,
    Name = `...2`,
    VariableNames = `...3`,
    Description = `...4`
  ) %>%
  filter(Name %in% c("AHSnpa11bp", "AHSnpa11ba"))
```

```{r}
# Define the search terms
search_terms <- c("grain", "plasma", "glucose gender", "HbA1c", "\\bALT\\b", "GGT", "identifier", "BMI", "\\bage\\b", "\\bsex of person\\b", "diabetes")

Possible_Variables <- X_all_File_variables %>%
  filter(grepl(paste(search_terms, collapse = "|"), Description, ignore.case = TRUE)) %>%
  select(VariableNames, Description) %>%
  distinct()
```

```{r}
bp_bb <- bind_rows(raw_bp, raw_bb)

columns_to_keep <- Possible_Variables$VariableNames

filtered_bp_bb <- bp_bb %>%
  select(any_of(columns_to_keep))

kept_columns_df <- Possible_Variables %>%
  filter(VariableNames %in% names(filtered_bp_bb))

kept_columns_df %>%
  kable(col.names = c("Variable Name", "Description"),
        caption = "Kept Variables and Their Descriptions") %>%
  print()
```

There are some variables that share the same Variable Name but different in their descriptions.

```{r}
# Create a case-insensitive regex pattern
search_pattern <- paste0("(?i)", paste(search_terms, collapse = "|"))

# Add a column to the filtered_rows that identifies the matching search term
kept_columns_df <- Possible_Variables %>%
  mutate(MatchingTerm = str_extract(tolower(Description), search_pattern)) %>%
  filter(VariableNames %in% names(filtered_bp_bb))
```

```{r}
group_counts <- kept_columns_df %>%
  filter(!is.na(MatchingTerm)) %>%
  group_by(MatchingTerm) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  arrange(MatchingTerm)

group_counts %>%
  kable(col.names = c("Matching Term", "Count"),
        caption = "Count of Entries for Each Matching Term") %>%
  print()
```

```{r}
grouped_output <- kept_columns_df %>%
  filter(!is.na(MatchingTerm)) %>%  # Ensure there are no NA values in MatchingTerm
  arrange(MatchingTerm) %>%
  select(MatchingTerm, VariableNames, Description)

grouped_output %>%
  kable(col.names = c("Matching Term", "Variable Name", "Description"),
        caption = "Kept Variables and Their Descriptions Grouped by Matching Terms") %>%
  print()
```
# Merging Data using ABSPID
```{r}
merged_df <- merge(raw_bb, raw_bp, by = "ABSPID")
columns_to_keep <- grouped_output$VariableNames
columns_to_keep <- as.character(columns_to_keep)
filtered_merged_df <- merged_df[, colnames(merged_df) %in% columns_to_keep]
```
# Type Change
```{r}
filtered_merged_df$ABSPID <- as.character(filtered_merged_df$ABSPID)

unique_counts <- sapply(filtered_merged_df, function(x) length(unique(x)))

continuous_vars <- names(unique_counts[unique_counts > 17 & unique_counts < 1000])
factor_vars <- names(unique_counts[unique_counts <= 17])

filtered_merged_df[continuous_vars] <- lapply(filtered_merged_df[continuous_vars], as.integer)

filtered_merged_df[factor_vars] <- lapply(filtered_merged_df[factor_vars], as.factor)

filtered_merged_df$ABSPID <- as.character(filtered_merged_df$ABSPID)
```
## Convert Specific Values (0, 8, 97) to Missing Values (NA) in Factor Variables
```{r}
magic_vals <- c(97, 8, 0)

for (col in names(filtered_merged_df)) {
  if (is.factor(filtered_merged_df[[col]])) {
    filtered_merged_df[[col]] <- as.character(filtered_merged_df[[col]])
    filtered_merged_df[[col]][filtered_merged_df[[col]] %in% as.character(magic_vals)] <- NA
    filtered_merged_df[[col]] <- as.factor(filtered_merged_df[[col]])
  }
}

str(filtered_merged_df)
```
## Drop "LEVELP" column
```{r}
filtered_merged_df <- filtered_merged_df[, !(names(filtered_merged_df) %in% "LEVELP")]
summary(filtered_merged_df)

write.csv(filtered_merged_df, "ResponseVariables_Cleaned.csv", row.names = FALSE)
```